### ISSUE TITLE
How to listen for the Hangup Packets?

### ISSUE THREAD

**Issue by wingoku** [GleasonK/pubnub-android-webrtc#1]
I am trying to get notified when a User Y rejects the call of User X. User Y publishes the Hangup package like mentioned [here](https://github.com/GleasonK/android-webrtc-api#static-methods-hangup-and-user-message) but there is no documentation on how to and where should we listen for the Hangup message on the Caller's app?

**Comment by wingoku** [comment]
@GleasonK May be you can provide a little heads up here :)

**Comment by GleasonK** [comment]
Thank you for bringing this to my attention, I will update the API shortly. Documentation on classes can be found [here](http://kevingleason.me/android-webrtc-api/). 

I looked at the code quickly, and it appears as though all hangups are synonymous with peer connections closed. So you can use the [onPeerConnectionClosed(PnPeer peer)](https://github.com/GleasonK/android-webrtc-api#pnrtclistener-callbacks) callback.

Let me know if this helped!
