### ISSUE TITLE
onAddRemoteStream ,onRemoveRemoteStream not called

### ISSUE THREAD

**Issue by hungtm288** [GleasonK/pubnub-android-webrtc#4]
great app but i get problem with build video call application.

onAddRemoteStream ,onRemoveRemoteStream not called, "Connecting..." still visible.

i geted source code from : https://github.com/GleasonK/AndroidRTC/tree/master/app/src/main/java/me/kevingleason/androidrtc

can you help me to resolve?

**Comment by rafaelanastacioalves** [comment]
What happened with this issue?

**Comment by abhilash-behera** [comment]
Even I have the same issue
